// ─── Per-Card Knowledge Base for Ask PIN ────────────────────────────────────
// Keyed by section ID from layoutConfig.ts DEFAULT_SECTIONS.

export interface SectionKB {
  /** What this card shows — 2-3 sentence explanation */
  explanation: string;
  /** What to look for / what matters */
  lookFor: string;
  /** What action to take based on this card */
  action: string;
  /** Pre-written FAQ pairs */
  faq: { q: string; keywords: string[]; a: string }[];
}

export const SECTION_KB: Record<string, SectionKB> = {
  // ── Federal Management Center (FMC) ────────────────────────────────────────

  usmap: {
    explanation: 'Interactive map of all monitoring stations across the US. Each dot represents a USGS, EPA, or state water quality monitoring point with color-coded status indicators.',
    lookFor: 'Clusters of red/amber stations indicate regional water quality stress. Zoom in to see individual station details and recent readings.',
    action: 'Click any station marker to see its latest data. Use the state filter to focus on a jurisdiction. Dense red clusters warrant further investigation via the state-by-state table.',
    faq: [
      { q: 'What do the colors mean?', keywords: ['color', 'colors', 'red', 'green', 'amber', 'dot'],
        a: 'Green stations are within normal parameters. Amber indicates elevated readings that may need monitoring. Red flags active exceedances or violations requiring attention.' },
      { q: 'How often is the map updated?', keywords: ['update', 'refresh', 'often', 'frequency', 'fresh'],
        a: 'Station data refreshes daily via the rebuild cron jobs. Real-time USGS sentinel stations update more frequently when alerts are active.' },
    ],
  },

  situation: {
    explanation: 'High-level snapshot of the current national water quality situation. Aggregates key metrics — impairment counts, active violations, and trend direction — into a quick-read summary.',
    lookFor: 'Rising violation counts or worsening trend arrows signal emerging issues. Compare current values to 30-day averages to assess whether conditions are improving or deteriorating.',
    action: 'Use the situation summary to prioritize your review. If violations are trending up, drill into the state-by-state table to identify the source states.',
    faq: [
      { q: 'What counts as a violation?', keywords: ['violation', 'violations', 'what', 'count'],
        a: 'A violation occurs when a measured parameter (e.g., E. coli, dissolved oxygen, nitrates) exceeds EPA or state water quality standards for that waterbody\'s designated use.' },
    ],
  },

  impairmentprofile: {
    explanation: 'National breakdown of waterbody impairments from EPA ATTAINS data. Shows how many waterbodies are assessed, impaired, and have TMDLs in place across all states.',
    lookFor: 'Watch for states with high impairment-to-assessment ratios — they have more water quality problems relative to how much they have assessed. Low TMDL coverage means impairments lack cleanup plans.',
    action: 'Use this to prioritize which states need compliance attention. States with many impairments but few TMDLs are falling behind on restoration planning.',
    faq: [
      { q: 'What is an impairment?', keywords: ['impairment', 'impaired', '303d', 'what'],
        a: 'An impairment means a waterbody does not meet water quality standards for its designated use (swimming, fishing, drinking water, etc.). Impaired waters are listed under Clean Water Act Section 303(d).' },
      { q: 'What is a TMDL?', keywords: ['tmdl', 'total', 'maximum', 'daily', 'load'],
        a: 'A Total Maximum Daily Load (TMDL) is a regulatory plan that sets the maximum amount of a pollutant a waterbody can receive and still meet water quality standards. It allocates pollution limits among sources.' },
      { q: 'Where does this data come from?', keywords: ['source', 'data', 'where', 'come', 'attains'],
        a: 'This data comes from EPA ATTAINS (Assessment, TMDL Tracking and Implementation System), which aggregates state-reported water quality assessments under the Clean Water Act.' },
    ],
  },

  'ai-water-intelligence': {
    explanation: 'AI-generated insights analyzing water quality data patterns across all monitored states. Identifies anomalies, emerging risks, and actionable recommendations.',
    lookFor: 'Critical-severity insights require immediate attention. Predictive insights warn about developing trends before they become violations.',
    action: 'Review critical insights first and delegate to the relevant state team. Use predictive insights for proactive planning and resource allocation.',
    faq: [
      { q: 'How are insights generated?', keywords: ['generated', 'how', 'ai', 'create', 'work'],
        a: 'Insights are generated by analyzing water quality data, permit violations, and monitoring trends using AI models. The system runs daily, comparing current conditions against historical baselines to identify significant changes.' },
      { q: 'Are AI insights always accurate?', keywords: ['accurate', 'accuracy', 'reliable', 'trust', 'wrong'],
        a: 'AI insights are analytical aids, not definitive findings. They highlight patterns worth investigating but should be verified against source data before taking action. The underlying data (ATTAINS, SDWIS, ICIS) is authoritative.' },
    ],
  },

  'national-briefing': {
    explanation: 'Auto-generated national intelligence briefing synthesizing the most important water quality developments across all states into an executive-ready summary.',
    lookFor: 'Key items flagged as "action required" or "escalation needed." Compare week-over-week changes to detect emerging interstate issues.',
    action: 'Use this briefing for leadership updates and cross-agency coordination. Items flagged for escalation should be routed to the appropriate program office.',
    faq: [
      { q: 'How often is the briefing updated?', keywords: ['often', 'update', 'refresh', 'frequency'],
        a: 'The national briefing regenerates daily during the early morning cron cycle, incorporating the latest data from all monitoring sources.' },
    ],
  },

  'sentinel-briefing': {
    explanation: 'Real-time health status of the USGS sentinel monitoring network. Shows which stations are reporting normally, which have alerts, and which are offline.',
    lookFor: 'Offline stations create coverage gaps. Stations with active alerts may indicate developing water quality events that need investigation.',
    action: 'For offline stations, coordinate with USGS for restoration. For alert stations, cross-reference with the waterbody detail to assess severity.',
    faq: [
      { q: 'What is a sentinel station?', keywords: ['sentinel', 'station', 'what'],
        a: 'Sentinel stations are high-priority USGS monitoring points that provide continuous real-time water quality measurements (temperature, dissolved oxygen, conductivity, turbidity, pH) at critical locations.' },
    ],
  },

  'air-quality-briefing': {
    explanation: 'Current air quality conditions relevant to watershed health. Wildfire smoke, industrial emissions, and atmospheric deposition can impact water quality downstream.',
    lookFor: 'AQI readings above 100 (Unhealthy for Sensitive Groups) near watersheds with active monitoring. Wildfire smoke events can cause short-term water quality degradation.',
    action: 'Cross-reference poor air quality areas with downstream monitoring stations. Schedule additional sampling after significant air quality events.',
    faq: [],
  },

  'flood-status': {
    explanation: 'Current river flood stage status from USGS and NWS data. Shows which river gauges are at or above flood stage across the country.',
    lookFor: 'Gauges at major or moderate flood stage. Flooding can cause sewage overflows, mobilize pollutants, and compromise drinking water intakes.',
    action: 'For flood-stage rivers, check downstream drinking water systems and issue advisories if intakes are threatened. Coordinate with emergency management.',
    faq: [
      { q: 'What are flood stages?', keywords: ['flood', 'stage', 'stages', 'level', 'levels'],
        a: 'Flood stages are thresholds set by NWS: Action (minor flooding possible), Minor (minimal property damage), Moderate (some road/building flooding), Major (extensive flooding, evacuations likely).' },
    ],
  },

  'flood-risk-summary': {
    explanation: 'Aggregated flood risk assessment at the watershed level, showing which HUC regions have elevated flood probability based on current conditions and forecasts.',
    lookFor: 'Watersheds with multiple gauges near flood stage have higher systemic risk. Compare to historical flood frequency for context.',
    action: 'Prioritize monitoring and community alerts for high-risk watersheds. Pre-position sampling resources for post-flood water quality assessment.',
    faq: [],
  },

  'briefing-actions': {
    explanation: 'Consolidated list of action items generated from all briefing sources. Each action has a priority level, responsible entity, and recommended deadline.',
    lookFor: 'High-priority actions with upcoming deadlines. Actions that have been pending for more than 7 days may need escalation.',
    action: 'Assign each action to the appropriate team. Track completion through the dashboard and escalate overdue items.',
    faq: [],
  },

  'delta-changelog': {
    explanation: 'Log of significant data changes detected between daily rebuilds. Shows what moved — new impairments listed, violations opened/closed, stations added/removed.',
    lookFor: 'Large batch changes (many new violations in one state) may indicate a reporting dump or real event. Sudden drops could mean data quality issues.',
    action: 'Investigate large delta spikes to distinguish between genuine events and data-quality artifacts. Use the changelog to maintain audit trails.',
    faq: [],
  },

  'pol-active-situations': {
    explanation: 'Currently active environmental situations with political visibility — contamination events, enforcement actions, community complaints, or media coverage.',
    lookFor: 'Situations escalating in media or public attention. Multiple overlapping situations in one jurisdiction compound political risk.',
    action: 'Prepare talking points for each active situation. Coordinate messaging with communications and legislative affairs teams.',
    faq: [],
  },

  'pol-talking-points': {
    explanation: 'Pre-drafted talking points for leadership briefings and public communications, tailored to current water quality conditions and active situations.',
    lookFor: 'Points marked as "sensitive" or "developing" need extra review before use. Verify data currency — talking points reflect the last briefing cycle.',
    action: 'Customize talking points for your specific audience and share with communications teams. Flag any points that need legal review.',
    faq: [],
  },

  'pol-constituent-concerns': {
    explanation: 'Aggregated constituent inquiries and complaints related to water quality, mapped to the relevant monitoring data and regulatory context.',
    lookFor: 'Spikes in concerns about a specific area or contaminant. Recurring concerns that correlate with actual monitoring data deserve priority response.',
    action: 'Route constituent concerns to the appropriate regional office. For data-backed concerns, prepare a response with supporting monitoring evidence.',
    faq: [],
  },

  'pol-funding-wins': {
    explanation: 'Recently secured grants, appropriations, and project funding for water quality and infrastructure projects.',
    lookFor: 'New funding that can be highlighted in communications. Projects moving from funding to implementation phase.',
    action: 'Coordinate announcement timing with communications. Ensure funded projects are tracked through implementation in the infrastructure section.',
    faq: [],
  },

  'pol-funding-risks': {
    explanation: 'Funding streams at risk due to policy changes, budget cuts, sequestration, or expiring authorizations.',
    lookFor: 'Funding sources with imminent expiration dates or proposed cuts. Programs that depend on at-risk funding for ongoing operations.',
    action: 'Brief leadership on at-risk funding and prepare contingency plans. Coordinate advocacy efforts for endangered appropriations.',
    faq: [],
  },

  'pol-regulatory-deadlines': {
    explanation: 'Upcoming regulatory deadlines for rulemakings, permit renewals, reporting requirements, and compliance milestones.',
    lookFor: 'Deadlines within the next 30-60 days that require agency action. Deadlines at risk of being missed.',
    action: 'Ensure responsible offices are tracking each deadline. Escalate any at risk of being missed to senior leadership.',
    faq: [],
  },

  'pol-ej-exposure': {
    explanation: 'Environmental justice analysis showing water quality burdens on disadvantaged communities. Maps pollution exposure to demographic vulnerability.',
    lookFor: 'Communities with both high pollution exposure and high vulnerability scores. Areas where impairments overlap with disadvantaged census tracts.',
    action: 'Prioritize EJ communities for enforcement attention and infrastructure investment. Use this data to support Justice40 initiative compliance.',
    faq: [
      { q: 'What is environmental justice?', keywords: ['environmental', 'justice', 'ej', 'what'],
        a: 'Environmental justice means ensuring that no community bears a disproportionate share of environmental burdens. In water quality, this means ensuring disadvantaged communities have equal access to clean water and are not disproportionately affected by pollution.' },
    ],
  },

  'pol-media-ready-grades': {
    explanation: 'Simple letter grades for each state\'s water quality performance, designed to be easily communicated to media and public audiences.',
    lookFor: 'Grade changes — states moving up or down. F-grade states that need immediate attention and communication strategy.',
    action: 'Prepare communications for any significant grade changes. Use grades in public reporting and congressional briefings.',
    faq: [],
  },

  'pol-peer-comparison': {
    explanation: 'Side-by-side comparison of states with similar characteristics (population, geography, industrial mix) to contextualize performance.',
    lookFor: 'States significantly underperforming their peer group. Best-practice states that can serve as models for improvement.',
    action: 'Use peer comparisons to set realistic improvement targets and identify transferable best practices.',
    faq: [],
  },

  'pol-council-agenda': {
    explanation: 'Suggested agenda items for interagency council meetings based on current water quality conditions and active issues.',
    lookFor: 'High-priority items that should lead the agenda. Cross-cutting issues that affect multiple agencies or programs.',
    action: 'Share with council leadership for agenda finalization. Prepare supporting materials for each suggested item.',
    faq: [],
  },

  aiinsights: {
    explanation: 'Combined AI-generated insights across all data sources — ATTAINS, SDWIS, ICIS, USGS — providing a unified analytical view of national water quality.',
    lookFor: 'Insights tagged "critical" signal immediate issues. Cross-source insights (where multiple data sources confirm the same trend) are highest confidence.',
    action: 'Triage critical insights immediately. Use cross-source confirmations to build strong cases for enforcement or resource allocation.',
    faq: [
      { q: 'What data sources feed into insights?', keywords: ['source', 'sources', 'data', 'feed', 'what'],
        a: 'Insights draw from ATTAINS (impairments), SDWIS (drinking water violations), ICIS/ECHO (permit enforcement), USGS NWIS (monitoring data), and NWS (weather/flood data).' },
    ],
  },

  'wq-domain-tabs': {
    explanation: 'Tabbed view breaking water quality data into domains — nutrients, bacteria, metals, organics, physical parameters. Allows focused analysis by contaminant category.',
    lookFor: 'Domains with the most exceedances relative to monitoring coverage. Emerging contaminant categories showing upward trends.',
    action: 'Use domain tabs to investigate specific contaminant classes when insights flag an issue. Compare domains across states to identify national patterns.',
    faq: [],
  },

  networkhealth: {
    explanation: 'Composite score assessing the health and coverage of the national monitoring network. Factors in station density, data currency, and parameter coverage.',
    lookFor: 'Scores below 70% indicate coverage gaps. States with declining network health may be losing monitoring capability.',
    action: 'Flag low-score states for monitoring capacity review. Coordinate with USGS and state agencies to address coverage gaps.',
    faq: [
      { q: 'How is the score calculated?', keywords: ['score', 'calculated', 'how', 'formula'],
        a: 'The network health score combines station density per watershed area, data freshness (% of stations reporting within 24h), and parameter coverage (how many key parameters each station monitors).' },
    ],
  },

  nationalimpact: {
    explanation: 'Quantified national impact of water quality treatment and restoration efforts. Shows pollutant load reductions, restored waterbodies, and treatment capacity improvements.',
    lookFor: 'Year-over-year improvement trends. Categories where treatment impact is stalling or declining despite investment.',
    action: 'Use impact data to justify continued funding and demonstrate program effectiveness. Investigate stalling categories for root causes.',
    faq: [],
  },

  priorityqueue: {
    explanation: 'Ranked list of states and waterbodies requiring priority attention based on severity, trend direction, compliance risk, and political sensitivity.',
    lookFor: 'Items at the top of the queue with worsening trends. Items that have been in the queue for extended periods without resolution.',
    action: 'Assign top-queue items to regional teams with specific deadlines. Review queue weekly to track progress and re-prioritize as conditions change.',
    faq: [],
  },

  coveragegaps: {
    explanation: 'Map and list of areas with insufficient monitoring coverage — places where water quality conditions are unknown due to lack of stations or stale data.',
    lookFor: 'Large geographic gaps, especially near known pollution sources or population centers. States with systematically poor coverage.',
    action: 'Prioritize gap areas for new monitoring station deployment. Use satellite and modeled data to estimate conditions in unmonitored areas.',
    faq: [],
  },

  statebystatesummary: {
    explanation: 'Comprehensive table showing key water quality metrics for every state: impairments, violations, monitoring coverage, enforcement actions, and trend indicators.',
    lookFor: 'States with multiple red indicators across categories. States where metrics are worsening compared to the previous period.',
    action: 'Use this table for comparative analysis and resource allocation decisions. Click any state row to drill into its detailed profile.',
    faq: [
      { q: 'Can I sort or filter the table?', keywords: ['sort', 'filter', 'search', 'find'],
        a: 'Yes — click any column header to sort. Use the search box to filter by state name. You can also filter by region or performance tier.' },
    ],
  },

  icis: {
    explanation: 'National NPDES permit enforcement data from EPA ICIS/ECHO. Shows facilities in significant non-compliance, enforcement actions, and penalty assessments.',
    lookFor: 'Facilities in significant non-compliance for extended periods. States with high violation rates but low enforcement activity.',
    action: 'Prioritize long-standing SNC facilities for escalated enforcement. Investigate states with enforcement gaps to determine if resources or policy changes are needed.',
    faq: [
      { q: 'What is NPDES?', keywords: ['npdes', 'permit', 'what'],
        a: 'The National Pollutant Discharge Elimination System (NPDES) is the Clean Water Act permit program that regulates point source discharges to waters of the US. Facilities must obtain permits that set pollutant limits.' },
      { q: 'What is significant non-compliance?', keywords: ['snc', 'significant', 'non-compliance', 'noncompliance'],
        a: 'Significant Non-Compliance (SNC) means a facility has serious permit violations — exceedances of effluent limits by specified margins, violations of compliance schedules, or failure to report. SNC triggers mandatory enforcement response.' },
    ],
  },

  sdwis: {
    explanation: 'Drinking water safety data from EPA SDWIS. Shows public water system violations, health-based exceedances, and monitoring/reporting failures nationwide.',
    lookFor: 'Health-based violations (MCL exceedances) are the most serious. Systems with recurring violations or treatment technique failures need urgent attention.',
    action: 'Prioritize health-based violations for immediate follow-up. Systems with repeated failures may need enforcement escalation or technical assistance.',
    faq: [
      { q: 'What is an MCL?', keywords: ['mcl', 'maximum', 'contaminant', 'level'],
        a: 'A Maximum Contaminant Level (MCL) is the highest level of a contaminant allowed in drinking water, set by EPA to protect public health. Exceeding an MCL is a violation requiring public notification and corrective action.' },
      { q: 'What is SDWIS?', keywords: ['sdwis', 'what', 'safe', 'drinking'],
        a: 'The Safe Drinking Water Information System (SDWIS) is EPA\'s database tracking public water systems, violations, and enforcement actions under the Safe Drinking Water Act.' },
    ],
  },

  groundwater: {
    explanation: 'Groundwater monitoring data from USGS NWIS. Shows well water levels, quality parameters, and trends for aquifers across the country.',
    lookFor: 'Declining water table levels and rising contaminant concentrations. Aquifers showing stress from over-extraction or contamination migration.',
    action: 'Flag stressed aquifers for enhanced monitoring. Coordinate with state programs on groundwater protection and remediation needs.',
    faq: [
      { q: 'Where does groundwater data come from?', keywords: ['source', 'data', 'where', 'come', 'nwis', 'usgs'],
        a: 'Groundwater data comes from USGS National Water Information System (NWIS), which collects data from a nationwide network of monitoring wells measuring water levels and quality parameters.' },
    ],
  },

  sla: {
    explanation: 'Service Level Agreement compliance metrics showing whether data processing, alerts, and reporting are meeting defined performance targets.',
    lookFor: 'SLA metrics below target thresholds. Recurring misses on the same metric indicate systemic capacity or process issues.',
    action: 'Address SLA misses by identifying bottlenecks. Persistent failures may require infrastructure upgrades or process redesign.',
    faq: [],
  },

  'scorecard-kpis': {
    explanation: 'Key Performance Indicators for the national water quality program. Tracks progress against strategic goals for impairment reduction, compliance rates, and monitoring coverage.',
    lookFor: 'KPIs trending away from targets. Leading indicators that predict future target misses.',
    action: 'Report KPI status to program leadership. For off-track KPIs, develop corrective action plans with specific milestones.',
    faq: [],
  },

  'scorecard-grades': {
    explanation: 'Letter grades (A-F) for each state based on a composite of water quality, compliance, monitoring, and enforcement metrics.',
    lookFor: 'Grade changes from the previous period — both improvements and declines. States clustered at D/F grades need systemic intervention.',
    action: 'Celebrate improving states and investigate declining ones. Use grades in annual program reports and strategic planning.',
    faq: [
      { q: 'How are grades calculated?', keywords: ['grade', 'grades', 'calculated', 'how', 'formula'],
        a: 'Grades combine multiple weighted factors: impairment rate (25%), compliance rate (25%), monitoring coverage (20%), enforcement responsiveness (15%), and trend direction (15%). Weights can be adjusted in scorecard settings.' },
    ],
  },

  'scorecard-rankings': {
    explanation: 'Top and bottom performing states ranked by composite water quality score. Quick identification of leaders and laggards.',
    lookFor: 'States that moved significantly in rankings. Bottom-ranked states with worsening trajectories need immediate attention.',
    action: 'Share rankings with regional offices for accountability. Connect top-performing states with bottom-performing peers for knowledge transfer.',
    faq: [],
  },

  'scorecard-choropleth': {
    explanation: 'Color-coded US map showing state grades geographically. Reveals regional patterns in water quality performance.',
    lookFor: 'Regional clusters of poor performance that may indicate shared challenges (drought, industrial corridors, agricultural runoff).',
    action: 'Use geographic patterns to design regional intervention strategies rather than state-by-state approaches.',
    faq: [],
  },

  'scorecard-trends': {
    explanation: 'Trend cards showing the direction and velocity of change for key metrics over time. Sparkline charts for quick visual assessment.',
    lookFor: 'Accelerating negative trends that may not yet show in current grades. Positive trends that confirm program investments are working.',
    action: 'Flag accelerating negative trends for pre-emptive action. Document positive trends for program justification.',
    faq: [],
  },

  'reports-hub': {
    explanation: 'Central hub for generating, viewing, and downloading federal water quality reports. Includes standard templates and custom report builder.',
    lookFor: 'Reports due within the next reporting cycle. Draft reports awaiting review or approval.',
    action: 'Generate required reports on schedule. Use custom reports for ad-hoc analysis requests from leadership.',
    faq: [],
  },

  'trends-dashboard': {
    explanation: 'Multi-year trend analysis dashboard showing how water quality metrics have evolved over time. Supports custom date ranges and metric selection.',
    lookFor: 'Long-term trends that differ from short-term patterns. Inflection points where trends changed direction.',
    action: 'Use trend data for strategic planning and policy evaluation. Identify programs that coincide with positive trend changes.',
    faq: [],
  },

  'policy-tracker': {
    explanation: 'Tracks pending and recently enacted policy and regulatory changes affecting water quality programs at federal, state, and local levels.',
    lookFor: 'Policies entering comment periods or final rule stages. Regulatory changes that affect multiple programs or require implementation planning.',
    action: 'Submit comments on proposed rules. Begin implementation planning for final rules with upcoming effective dates.',
    faq: [],
  },

  'contaminants-tracker': {
    explanation: 'Monitors emerging contaminants — PFAS, microplastics, pharmaceuticals, and others not yet fully regulated but increasingly detected in water supplies.',
    lookFor: 'Contaminants with rising detection frequency or concentration trends. New EPA health advisories or proposed regulations for emerging contaminants.',
    action: 'Prioritize monitoring for contaminants trending upward. Prepare for regulatory changes by assessing current detection capabilities.',
    faq: [
      { q: 'What are PFAS?', keywords: ['pfas', 'forever', 'chemicals', 'what'],
        a: 'PFAS (per- and polyfluoroalkyl substances) are a large class of synthetic chemicals used in many products. Called "forever chemicals" because they don\'t break down in the environment. EPA has set enforceable limits for several PFAS in drinking water.' },
    ],
  },

  'sentinel-alerts-placeholder': {
    explanation: 'Placeholder for the upcoming sentinel alert system that will provide real-time notifications when monitoring stations detect critical water quality changes.',
    lookFor: 'This section will show live alerts once fully operational. Currently displays system status and expected launch timeline.',
    action: 'No action needed currently. Review the timeline for planned deployment to your jurisdiction.',
    faq: [],
  },

  'interagency-hub': {
    explanation: 'Cross-agency coordination hub connecting EPA water quality programs with USGS, USDA, FEMA, Army Corps, and state agencies on shared water issues.',
    lookFor: 'Active coordination requests and pending inter-agency actions. Issues requiring multi-agency response (flood events, contamination incidents).',
    action: 'Route coordination requests to the appropriate program office. Ensure response timelines are met for inter-agency commitments.',
    faq: [],
  },

  'data-latency': {
    explanation: 'Tracks how fresh each data source is — showing the last successful update time and any delays for ATTAINS, SDWIS, ICIS, USGS, and other feeds.',
    lookFor: 'Sources with data older than expected refresh cycles. Multiple sources going stale simultaneously may indicate infrastructure issues.',
    action: 'Investigate stale data sources to determine if the issue is upstream (agency reporting) or internal (cron/pipeline failure).',
    faq: [],
  },

  'funding-landscape': {
    explanation: 'Overview of federal water quality funding programs — SRF, WIIN Act, BIL/IIJA allocations, and competitive grants. Shows total available funding and utilization rates.',
    lookFor: 'Programs with low utilization rates (money available but not being used). Upcoming allocation deadlines.',
    action: 'Connect states with low utilization to technical assistance. Ensure all allocations are claimed before deadlines.',
    faq: [],
  },

  'funding-deadlines': {
    explanation: 'Calendar of upcoming funding application deadlines, reporting due dates, and allocation milestones.',
    lookFor: 'Deadlines within the next 30 days. Programs where applications are trending below historical rates.',
    action: 'Send deadline reminders to eligible applicants. Identify barriers for programs with low application rates.',
    faq: [],
  },

  'funding-state': {
    explanation: 'State-level funding snapshot showing how much each state has received, obligated, and drawn down across federal water programs.',
    lookFor: 'States with large unobligated balances (not putting money to work). States with high drawdown rates nearing allocation limits.',
    action: 'Work with slow-spending states to identify and remove barriers. Plan supplemental allocations for states nearing limits.',
    faq: [],
  },

  'funding-matrix': {
    explanation: 'Matrix mapping specific impairment types to eligible funding programs. Helps identify which funding sources can address which water quality problems.',
    lookFor: 'Impairment types with multiple funding options (more flexibility) vs. those with few or none (funding gaps).',
    action: 'Use the matrix to guide states toward appropriate funding sources for their specific impairment challenges.',
    faq: [],
  },

  'grant-outcomes': {
    explanation: 'Historical analysis of grant-funded project outcomes. Shows which types of investments have produced the best water quality improvements.',
    lookFor: 'Project types with high success rates and strong return on investment. Categories where outcomes have been disappointing.',
    action: 'Use outcome data to prioritize future funding toward proven approaches. Investigate low-outcome categories for lessons learned.',
    faq: [],
  },

  'funding-gap': {
    explanation: 'Analysis of the gap between identified water quality infrastructure needs and available funding. Quantifies the shortfall by state and category.',
    lookFor: 'States with the largest funding gaps relative to their needs. Categories (drinking water, stormwater, wastewater) with the biggest shortfalls.',
    action: 'Use gap analysis in budget justifications and policy advocacy. Target emergency funds to the most critical unmet needs.',
    faq: [],
  },

  'resolution-planner': {
    explanation: 'Interactive planner for building waterbody restoration and compliance resolution strategies. Guides users through selecting impairments, causes, and corrective actions.',
    lookFor: 'Open resolution plans that need updates. Waterbodies with multiple impairments requiring coordinated resolution strategies.',
    action: 'Create resolution plans for priority waterbodies. Review and update existing plans quarterly based on monitoring data.',
    faq: [],
  },

  'restoration-planner': {
    explanation: 'Planning tool for watershed restoration projects. Helps design, scope, and budget restoration activities based on impairment data and best management practices.',
    lookFor: 'Restoration opportunities with high predicted water quality improvement per dollar invested. Projects that address multiple impairments simultaneously.',
    action: 'Develop restoration plans for priority watersheds. Use the cost-effectiveness analysis to optimize limited restoration budgets.',
    faq: [],
  },

  'habitat-ecology': {
    explanation: 'Ecological and habitat data for watersheds. Shows species diversity, habitat quality indices, and ecological health indicators.',
    lookFor: 'Declining biodiversity trends. Habitat quality drops that correlate with water quality degradation in the same watershed.',
    action: 'Integrate ecological data with water quality planning. Prioritize restoration in areas where water quality improvements will benefit critical habitats.',
    faq: [],
  },

  'agricultural-nps': {
    explanation: 'Agricultural and non-point source pollution data. Tracks nutrient loading, sediment runoff, and pesticide detections from agricultural areas.',
    lookFor: 'Watersheds with increasing nutrient trends despite BMP implementation. Seasonal patterns in agricultural runoff (spring planting, fall harvest).',
    action: 'Coordinate with USDA and state agriculture agencies on high-loading watersheds. Evaluate BMP effectiveness and adjust conservation programs.',
    faq: [
      { q: 'What is non-point source pollution?', keywords: ['non-point', 'nonpoint', 'nps', 'what'],
        a: 'Non-point source (NPS) pollution comes from diffuse sources rather than a single pipe — agricultural runoff, urban stormwater, atmospheric deposition. It\'s the leading remaining cause of water quality impairments in the US.' },
    ],
  },

  'disaster-emergency': {
    explanation: 'Emergency and disaster response dashboard for water quality incidents. Tracks active emergencies, response resources, and affected water systems.',
    lookFor: 'Active emergencies requiring coordination. Developing situations (approaching storms, industrial incidents) that may impact water quality.',
    action: 'Coordinate response resources for active emergencies. Pre-position assets for developing situations based on risk assessment.',
    faq: [],
  },

  'military-installations': {
    explanation: 'Water quality monitoring data for military installations, including PFAS contamination tracking, groundwater status, and compliance with DoD environmental requirements.',
    lookFor: 'Installations with active PFAS plumes or expanding contamination. Facilities not meeting cleanup milestones.',
    action: 'Coordinate with DoD on installations falling behind cleanup schedules. Ensure affected communities have access to alternative water supplies.',
    faq: [
      { q: 'Why are military bases tracked?', keywords: ['military', 'base', 'bases', 'why', 'dod'],
        a: 'Military installations are significant sources of PFAS and other contaminants from firefighting foam (AFFF), industrial operations, and waste disposal. DoD is responsible for cleanup under CERCLA and often impacts surrounding community water supplies.' },
    ],
  },

  'waterfront-exposure': {
    explanation: 'Analysis of waterfront property and infrastructure exposure to water quality risks. Maps economic value at risk from impairments, flooding, and contamination.',
    lookFor: 'High-value areas with deteriorating water quality. Coastal properties exposed to both flooding and contamination risk.',
    action: 'Use exposure data for risk-informed infrastructure planning. Share with local governments for land use and development decisions.',
    faq: [],
  },

  'fund-srf': {
    explanation: 'State Revolving Fund (SRF) program dashboard showing Clean Water and Drinking Water SRF loan activity, fund balances, and project pipeline.',
    lookFor: 'States with low SRF utilization or growing fund balances (not lending enough). Projects in the pipeline that need to move forward.',
    action: 'Work with underperforming SRF programs to increase lending. Review project pipelines for shovel-ready projects.',
    faq: [
      { q: 'What is SRF?', keywords: ['srf', 'revolving', 'fund', 'what'],
        a: 'The State Revolving Fund is a federal-state partnership providing low-interest loans for water infrastructure. The Clean Water SRF funds wastewater projects; the Drinking Water SRF funds drinking water system improvements.' },
    ],
  },

  'infra-capital': {
    explanation: 'Capital improvement planning dashboard for water and wastewater infrastructure. Tracks project proposals, cost estimates, and funding alignment.',
    lookFor: 'Projects with secured funding that are ready to proceed. High-priority needs without funding commitments.',
    action: 'Advance funded projects through planning stages. Match unfunded priorities with appropriate funding sources from the funding matrix.',
    faq: [],
  },

  'infra-construction': {
    explanation: 'Active construction project tracker showing status, timeline, budget, and completion percentage for water infrastructure projects.',
    lookFor: 'Projects behind schedule or over budget. Milestones approaching in the next quarter.',
    action: 'Intervene on troubled projects early. Ensure milestone payments are processed on time for on-track projects.',
    faq: [],
  },

  'infra-green': {
    explanation: 'Green infrastructure dashboard tracking nature-based solutions — bioswales, rain gardens, permeable pavement, constructed wetlands — for stormwater management.',
    lookFor: 'Green infrastructure projects with demonstrated co-benefits (water quality + flood reduction + community amenity). Municipalities with ambitious green infrastructure targets.',
    action: 'Promote successful green infrastructure models. Connect interested communities with technical assistance and funding.',
    faq: [],
  },

  'location-report': {
    explanation: 'Detailed water quality report for a specific location. Aggregates all available data — monitoring, compliance, impairments, infrastructure — for a single geographic point.',
    lookFor: 'Multiple overlapping water quality issues at the same location. Discrepancies between monitoring data and compliance records.',
    action: 'Use location reports for site-specific decision-making, environmental review, and stakeholder communications.',
    faq: [],
  },

  disclaimer: {
    explanation: 'Platform disclaimer noting data sources, refresh schedules, and appropriate use of dashboard information.',
    lookFor: 'Review periodically to ensure you understand data limitations and appropriate use.',
    action: 'Share the disclaimer with anyone you distribute dashboard outputs to.',
    faq: [],
  },

  training: {
    explanation: 'Guided training modules for learning how to use the dashboard effectively. Covers navigation, data interpretation, and workflow best practices.',
    lookFor: 'New modules added for recently launched features. Modules you haven\'t completed yet.',
    action: 'Complete all training modules and encourage team members to do the same. Provide feedback on modules that need improvement.',
    faq: [],
  },
};

/**
 * Get KB entry for a section, falling back to a generic entry built from the label.
 */
export function getKB(sectionId: string, label: string): SectionKB {
  if (SECTION_KB[sectionId]) return SECTION_KB[sectionId];
  return {
    explanation: `This card displays data and analysis for "${label}." It aggregates relevant metrics and highlights key items that need your attention.`,
    lookFor: 'Focus on any highlighted items, trend indicators, or severity flags that call for action.',
    action: 'Review the highlighted items and determine whether follow-up investigation or action is needed.',
    faq: [],
  };
}
