"use client";

import React from "react";

/**
 * Opens a branded print window for a dashboard section.
 * Replaces the old per-component printSection() with a shared
 * implementation that uses the PEARL logo instead of an oyster emoji.
 */
export function brandedPrintSection(
  sectionId: string,
  title: string,
  subtitle?: string
): void {
  const el = document.getElementById(`section-${sectionId}`);
  if (!el) return;

  const win = window.open("", "_blank", "width=900,height=700");
  if (!win) return;

  const dateStr = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const subtitleHtml = subtitle
    ? `<p style="font-size:11px;color:#64748b;margin-top:2px;">${subtitle}</p>`
    : "";

  win.document.write(`<!DOCTYPE html><html><head><title>${title} — PEARL Intelligence Network</title>
    <style>
      * { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 24px; color: #1e293b; }
      .print-logo { text-align: center; margin-bottom: 8px; }
      .print-logo img { max-height: 50px; }
      .print-logo-fallback { font-size: 18px; font-weight: 700; color: #2563EB; text-align: center; margin-bottom: 8px; }
      .print-separator { border: none; border-top: 2px solid #2563EB; margin-bottom: 12px; }
      .print-header { padding-bottom: 12px; margin-bottom: 16px; }
      .print-header h1 { font-size: 16px; font-weight: 700; color: #1e3a5f; }
      .print-header p { font-size: 11px; color: #64748b; margin-top: 4px; }
      .print-content { font-size: 13px; line-height: 1.5; }
      .print-content table { width: 100%; border-collapse: collapse; margin: 8px 0; }
      .print-content th, .print-content td { border: 1px solid #e2e8f0; padding: 6px 8px; text-align: left; font-size: 12px; }
      .print-content th { background: #f8fafc; font-weight: 600; }
      .print-footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; text-align: center; }
      canvas, svg { max-width: 100%; }
      button, [role="button"] { display: none !important; }
      @media print {
        body { padding: 0; }
        body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      }
    </style>
  </head><body>
    <div class="print-logo">
      <img src="/Pearl-Logo-alt.png" alt="Project PEARL" onerror="this.style.display='none';document.getElementById('logo-fallback').style.display='block';" />
      <div id="logo-fallback" class="print-logo-fallback" style="display:none;">PROJECT PEARL</div>
    </div>
    <hr class="print-separator" />
    <div class="print-header">
      <h1>${title}</h1>
      ${subtitleHtml}
      <p>${dateStr} · Project PEARL</p>
    </div>
    <div class="print-content">${el.innerHTML}</div>
    <div class="print-footer">Generated by Project PEARL &mdash; project-pearl.org</div>
  </body></html>`);
  win.document.close();
  setTimeout(() => {
    win.print();
  }, 400);
}

/**
 * Small printer-icon button that calls brandedPrintSection.
 * Drop-in replacement for the old inline PrintBtn / <span onClick> patterns.
 */
export function BrandedPrintBtn({
  sectionId,
  title,
  subtitle,
}: {
  sectionId: string;
  title: string;
  subtitle?: string;
}) {
  // Dynamically import Printer icon to keep this file light
  // We use an inline SVG instead to avoid requiring lucide-react as a dependency here
  return React.createElement("button", {
    onClick: (e: React.MouseEvent) => {
      e.stopPropagation();
      brandedPrintSection(sectionId, title, subtitle);
    },
    className: "p-1 hover:bg-slate-200 rounded transition-colors",
    title: "Print this section",
    children: React.createElement("svg", {
      xmlns: "http://www.w3.org/2000/svg",
      width: 14,
      height: 14,
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: 2,
      strokeLinecap: "round",
      strokeLinejoin: "round",
      className: "text-slate-400",
      children: [
        React.createElement("polyline", { key: "p1", points: "6 9 6 2 18 2 18 9" }),
        React.createElement("path", { key: "p2", d: "M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" }),
        React.createElement("rect", { key: "p3", width: 12, height: 8, x: 6, y: 14 }),
      ],
    }),
  });
}
