/**
 * In-memory cache for pre-generated AI insights.
 *
 * Populated by the `generate-insights` cron job every 6 hours and served
 * instantly to users. Falls back to on-demand generation on cold start.
 * Uses debounced disk writes (10s) to avoid thrashing during the 408-call build.
 */

import { saveCacheToBlob, loadCacheFromBlob } from './blobPersistence';

/** A single AI-generated insight (predictive, anomaly, comparison, etc.). */
export interface CachedInsight {
  type: 'predictive' | 'anomaly' | 'comparison' | 'recommendation' | 'summary';
  severity: 'info' | 'warning' | 'critical';
  title: string;
  body: string;
  waterbody?: string;
  timeframe?: string;
}

/** A cached set of insights for a specific state+role combination. */
export interface CacheEntry {
  insights: CachedInsight[];
  generatedAt: string;
  signalsHash: string; // hash of signals data — only regenerate if this changes
  provider: string;
  urgentRefresh?: boolean; // true if generated by urgent cron due to active crisis
  enrichmentSummary?: string; // e.g. "2 critical USGS alerts, 1 beach closure"
}

type CacheKey = string; // format: "STATE:ROLE" e.g. "MD:MS4"

// ─── State ───────────────────────────────────────────────────────────────────

const cache = new Map<CacheKey, CacheEntry>();
let lastFullBuild: string | null = null;
let buildInProgress = false;
let _buildStartedAt = 0;
const BUILD_LOCK_TIMEOUT_MS = 12 * 60 * 1000; // 12 min — auto-clear stale locks

// ─── Disk Persistence (debounced — max once per 10s) ────────────────────────

let _diskLoaded = false;
let _savePending = false;
let _lastSaveTime = 0;
const SAVE_DEBOUNCE_MS = 10_000;

function loadFromDisk(): boolean {
  try {
    if (typeof process === 'undefined') return false;
    const fs = require('fs');
    const path = require('path');
    const file = path.join(process.cwd(), '.cache', 'ai-insights.json');
    if (!fs.existsSync(file)) return false;
    const raw = fs.readFileSync(file, 'utf-8');
    const data = JSON.parse(raw);
    if (!data?.entries || !Array.isArray(data.entries)) return false;

    cache.clear();
    for (const [key, entry] of data.entries) {
      cache.set(key, entry);
    }
    lastFullBuild = data.lastFullBuild || null;

    console.log(
      `[Insights Cache] Loaded from disk (${cache.size} entries, ` +
      `last build ${lastFullBuild || 'unknown'})`
    );
    return true;
  } catch {
    return false;
  }
}

function saveToDisk(): void {
  try {
    if (typeof process === 'undefined' || cache.size === 0) return;
    const fs = require('fs');
    const path = require('path');
    const dir = path.join(process.cwd(), '.cache');
    const file = path.join(dir, 'ai-insights.json');
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const payload = JSON.stringify({
      lastFullBuild,
      entries: Array.from(cache.entries()),
    });
    fs.writeFileSync(file, payload, 'utf-8');
    const sizeMB = (Buffer.byteLength(payload) / 1024 / 1024).toFixed(1);
    console.log(`[Insights Cache] Saved to disk (${sizeMB}MB, ${cache.size} entries)`);
  } catch {
    // Disk save is optional — fail silently
  }
}

function debouncedSaveToDisk(): void {
  const now = Date.now();
  if (now - _lastSaveTime >= SAVE_DEBOUNCE_MS) {
    _lastSaveTime = now;
    saveToDisk();
  } else if (!_savePending) {
    _savePending = true;
    setTimeout(() => {
      _savePending = false;
      _lastSaveTime = Date.now();
      saveToDisk();
    }, SAVE_DEBOUNCE_MS - (now - _lastSaveTime));
  }
}

function ensureDiskLoaded() {
  if (!_diskLoaded) {
    _diskLoaded = true;
    loadFromDisk();
  }
}

let _blobChecked = false;
/**
 * Ensure the insights cache is populated. Tries disk first, then Vercel Blob.
 * No-op if the cache already has entries.
 */
export async function ensureWarmed(): Promise<void> {
  ensureDiskLoaded();
  if (cache.size > 0) return;
  if (_blobChecked) return;
  _blobChecked = true;
  const data = await loadCacheFromBlob<{ lastFullBuild: string | null; entries: [string, CacheEntry][] }>('cache/insights.json');
  if (data?.entries && Array.isArray(data.entries)) {
    cache.clear();
    for (const [key, entry] of data.entries) {
      cache.set(key, entry);
    }
    lastFullBuild = data.lastFullBuild || null;
    console.warn(`[Insights Cache] Loaded from blob (${cache.size} entries, last build ${lastFullBuild || 'unknown'})`);
  }
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Build the cache lookup key for a given state and role.
 *
 * @param state - State abbreviation (e.g. "MD")
 * @param role  - User role (e.g. "Federal", "MS4")
 * @returns Cache key in "STATE:ROLE" format
 */
export function getCacheKey(state: string, role: string): CacheKey {
  return `${state.toUpperCase()}:${role}`;
}

/**
 * Compute a simple hash of signal data for change detection.
 * If the hash hasn't changed since the last build, regeneration is skipped.
 *
 * @param signals - Array of signal objects with type, severity, and title
 * @returns A base-36 hash string
 */
export function hashSignals(signals: any[]): string {
  const str = JSON.stringify(signals.map(s => `${s.type}:${s.severity}:${s.title}`).sort());
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return hash.toString(36);
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Retrieve cached insights for a state+role. Returns null if not cached or stale (>7 hours).
 *
 * @param state - State abbreviation
 * @param role  - User role
 * @returns The cached entry, or null if missing/stale
 */
export function getInsights(state: string, role: string): CacheEntry | null {
  ensureDiskLoaded();
  const entry = cache.get(getCacheKey(state, role));
  if (!entry) return null;

  // Stale after 7 hours (gives buffer past 6hr cron)
  const age = Date.now() - new Date(entry.generatedAt).getTime();
  if (age > 7 * 60 * 60 * 1000) return null;

  return entry;
}

/**
 * Store insights for a state+role in the in-memory cache and trigger a debounced disk save.
 *
 * @param state - State abbreviation
 * @param role  - User role
 * @param entry - The insight cache entry to store
 */
export function setInsights(state: string, role: string, entry: CacheEntry): void {
  cache.set(getCacheKey(state, role), entry);
  debouncedSaveToDisk();
}

/**
 * Check if an insight build is currently running. Auto-clears stale locks older than 12 minutes.
 *
 * @returns Whether a build is in progress
 */
export function isBuildInProgress(): boolean {
  if (buildInProgress && _buildStartedAt > 0 && Date.now() - _buildStartedAt > BUILD_LOCK_TIMEOUT_MS) {
    console.warn('[Insights Cache] Auto-clearing stale build lock (>12 min)');
    buildInProgress = false;
    _buildStartedAt = 0;
  }
  return buildInProgress;
}

/**
 * Set or clear the build-in-progress lock.
 *
 * @param v - `true` to start build lock, `false` to release
 */
export function setBuildInProgress(v: boolean): void {
  buildInProgress = v;
  _buildStartedAt = v ? Date.now() : 0;
}

/**
 * Record the timestamp of the last complete insight build.
 * Forces an immediate disk save and persists the full cache to Vercel Blob.
 *
 * @param timestamp - ISO timestamp of build completion
 */
export async function setLastFullBuild(timestamp: string): Promise<void> {
  lastFullBuild = timestamp;
  saveToDisk(); // Force immediate save at end of build
  await saveCacheToBlob('cache/insights.json', {
    lastFullBuild,
    entries: Array.from(cache.entries()),
  });
}

/**
 * Get a summary of the current insights cache state.
 *
 * @returns Status object with build state, entry count, last build time, and reporting states
 */
export function getCacheStatus(): {
  status: 'idle' | 'building' | 'ready';
  entries: number;
  lastFullBuild: string | null;
  states: string[];
} {
  ensureDiskLoaded();
  const states = new Set<string>();
  for (const key of cache.keys()) {
    states.add(key.split(':')[0]);
  }
  return {
    status: buildInProgress ? 'building' : cache.size > 0 ? 'ready' : 'idle',
    entries: cache.size,
    lastFullBuild,
    states: [...states].sort(),
  };
}

/**
 * Clear all cached insights and reset the last-build timestamp.
 * Used for manual cache reset.
 */
export function clearInsightsCache(): void {
  cache.clear();
  lastFullBuild = null;
}
