"use client";

import React, { useRef } from "react";
import {
  CK, CONTAMINANT_LABELS, CONTAMINANT_COLORS, MODULE_CATS, CAT_COLORS,
  MODULES, CLIMATE_PROJECTIONS,
  fmt, fmtN,
  type Watershed, type CalcResult, type NGO, type CommunityEvent,
  type ModuleCategory, type ContaminantKey,
  type RcpScenario, type ClimateDecade,
} from "./treatmentData";

interface ExecutiveOutputProps {
  ws: Watershed;
  calc: CalcResult;
  timeline: number;
  target: number;
  selectedNGOs: NGO[];
  selectedEvents: CommunityEvent[];
  ngoValue: number;
  evtCostYr: number;
  onClose: () => void;
  climateScenario: RcpScenario;
  climateDecade: ClimateDecade;
  climateCalc: CalcResult | null;
  climateWs: Watershed;
}

export default function ExecutiveOutput({
  ws, calc, timeline, target, selectedNGOs, selectedEvents, ngoValue, evtCostYr, onClose,
  climateScenario, climateDecade, climateCalc, climateWs,
}: ExecutiveOutputProps) {
  const pdfRef = useRef<HTMLDivElement>(null);
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const communityTotal = evtCostYr * timeline;
  const lifecycleAll = calc.capex + calc.totalOpex + communityTotal;
  const netAfterGrants = Math.max(0, lifecycleAll - calc.grantTotal);

  /* ── PDF export ── */
  const handleExportPDF = async () => {
    const el = pdfRef.current;
    if (!el) return;

    // Show pdf-only, hide no-pdf
    const pdfOnlyEls = el.querySelectorAll<HTMLElement>(".pdf-only");
    const noPdfEls = el.querySelectorAll<HTMLElement>(".no-pdf");
    pdfOnlyEls.forEach(e => (e.style.display = "block"));
    noPdfEls.forEach(e => (e.style.display = "none"));

    try {
      const dateStr = new Date().toISOString().slice(0, 10);
      const filename = `PIN_Treatment_Plan_${ws.id}_${dateStr}.pdf`;

      const html2pdf = (await import("html2pdf.js")).default;
      await html2pdf()
        .set({
          margin: [0.3, 0.4, 0.7, 0.4],
          filename,
          image: { type: "jpeg", quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true, logging: false, letterRendering: true, windowWidth: 1000 },
          jsPDF: { unit: "in", format: "letter", orientation: "portrait" as const },
          pagebreak: { mode: ["css", "legacy"], before: [".pdf-page-break"], avoid: ["tr", ".exec-card", "section"] },
        })
        .from(el)
        .toPdf()
        .get("pdf")
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .then((pdf: any) => {
          const totalPages = pdf.internal.getNumberOfPages();
          const pageWidth = pdf.internal.pageSize.getWidth();

          pdf.setProperties({
            title: `PIN Treatment Plan \u2014 ${ws.name}`,
            author: "PIN",
            subject: "Treatment Planning \u2014 Not Regulatory Guidance",
            creator: "PIN v1.0 \u2014 pinwater.org",
          });

          for (let i = 1; i <= totalPages; i++) {
            pdf.setPage(i);
            // Watermark
            pdf.saveGraphicsState();
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            const gState = new (pdf as any).GState({ opacity: 0.08 });
            pdf.setGState(gState);
            pdf.setFontSize(48);
            pdf.setTextColor(150, 150, 150);
            pdf.text("PLANNING DRAFT", pageWidth / 2, 5.5, { angle: 45, align: "center" });
            pdf.restoreGraphicsState();
            // Footer
            pdf.setFontSize(7);
            pdf.setTextColor(128, 128, 128);
            pdf.text(
              "Generated by PIN (PEARL Intelligence Network). Not a regulatory determination, legal opinion, or engineering design.",
              0.4, 10.25,
            );
            pdf.text(
              "All cost estimates are planning-level approximations. Verify with primary agency data and qualified professionals.",
              0.4, 10.4,
            );
            pdf.text(`Page ${i} of ${totalPages}`, pageWidth - 0.4, 10.4, { align: "right" });
          }
        })
        .save();
    } finally {
      pdfOnlyEls.forEach(e => (e.style.display = ""));
      noPdfEls.forEach(e => (e.style.display = ""));
    }
  };

  /* ── Capex by category ── */
  const capexByCat = MODULE_CATS.map(cat => {
    const mods = calc.active.filter(m => m.cat === cat);
    if (!mods.length) return null;
    return { cat, total: mods.reduce((s, m) => s + m.totalCost, 0), mods };
  }).filter(Boolean) as { cat: ModuleCategory; total: number; mods: CalcResult["active"] }[];

  return (
    <div className="border-t-4 border-emerald-400 bg-slate-50">
      {/* Toolbar */}
      <div className="sticky top-0 z-20 bg-white border-b border-slate-200 px-6 py-2.5 flex items-center gap-3 no-pdf">
        <span className="text-[11px] font-bold text-slate-800 uppercase tracking-wider">Executive Summary</span>
        <div className="flex-1" />
        <button
          onClick={handleExportPDF}
          className="px-3 py-1.5 bg-slate-800 text-white text-[11px] font-bold rounded hover:bg-slate-700 transition-colors cursor-pointer"
        >
          Export PDF
        </button>
        <button
          onClick={onClose}
          className="px-3 py-1.5 border border-slate-300 text-slate-600 text-[11px] rounded hover:bg-slate-50 transition-colors cursor-pointer"
        >
          Close
        </button>
      </div>

      <div ref={pdfRef} className="max-w-[900px] mx-auto px-6 py-8 space-y-8">
        {/* ═══ 1. Branded Header ═══ */}
        <section className="exec-card">
          <div className="flex items-start justify-between">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <div className="w-2 h-2 rounded-full bg-emerald-400 shadow-[0_0_8px_theme(colors.emerald.400)]" />
                <span className="font-mono text-sm font-bold text-slate-800 tracking-[3px]">PIN</span>
                <span className="text-slate-300">|</span>
                <span className="text-sm text-slate-500">Treatment Plan</span>
              </div>
              <h1 className="font-serif text-2xl text-slate-900 leading-tight">{ws.name}</h1>
              <p className="text-xs text-slate-400 mt-1">
                HUC {ws.huc} &middot; {ws.state} &middot; Generated {today}
              </p>
            </div>
            <div className="text-right">
              <div className="text-[9px] text-slate-400 uppercase tracking-wider">Target Reduction</div>
              <div className="text-2xl font-bold font-mono text-slate-800">{target}%</div>
              <div className="text-[9px] text-slate-400">{timeline}-Year Timeline</div>
            </div>
          </div>
        </section>

        {/* ═══ 2. Watershed Context ═══ */}
        <section className="exec-card bg-white rounded-xl p-5 border border-slate-200 shadow-sm">
          <h2 className="text-xs font-bold text-slate-800 uppercase tracking-wider mb-3">Watershed Context</h2>
          <div className="grid grid-cols-5 gap-3 mb-4">
            {[
              { l: "Flow", v: fmtN(ws.flowMGD) + " MGD" },
              { l: "Area", v: fmtN(ws.acres) + " ac" },
              { l: "Salinity", v: ws.salinity + " ppt" },
              { l: "Baseline DO", v: ws.doMgL + " mg/L" },
              { l: "Treatable", v: ws.treatable + "%" },
            ].map(x => (
              <div key={x.l} className="text-center bg-slate-50 rounded-lg py-2">
                <div className="text-[8px] text-slate-400 uppercase tracking-wider">{x.l}</div>
                <div className="text-sm font-bold font-mono text-slate-800">{x.v}</div>
              </div>
            ))}
          </div>
          <p className="text-xs text-slate-500 mb-3">{ws.context}</p>
          <div className="flex gap-1.5 flex-wrap mb-4">
            {ws.causes.map(c => (
              <span key={c} className="text-[9px] bg-red-50 text-red-600 px-2 py-0.5 rounded">{c}</span>
            ))}
          </div>
          <div className="text-[9px] text-slate-400 uppercase tracking-wider font-mono mb-2">
            Baseline Contamination
          </div>
          {CK.map(k => {
            if (ws.baseline[k] === 0) return null;
            return (
              <div key={k} className="flex items-center gap-2 mb-1">
                <span className="w-16 text-[10px] text-slate-500 font-mono">{CONTAMINANT_LABELS[k].split(" / ")[0]}</span>
                <div className="flex-1 h-2 bg-slate-100 rounded-sm overflow-hidden">
                  <div
                    className="h-full rounded-sm"
                    style={{ width: `${ws.baseline[k]}%`, background: CONTAMINANT_COLORS[k], opacity: 0.7 }}
                  />
                </div>
                <span className="w-8 text-[10px] font-mono text-slate-600 text-right">{ws.baseline[k]}%</span>
              </div>
            );
          })}
        </section>

        {/* ═══ 3. Treatment Stack ═══ */}
        <section className="exec-card bg-white rounded-xl p-5 border border-slate-200 shadow-sm">
          <h2 className="text-xs font-bold text-slate-800 uppercase tracking-wider mb-3">Treatment Stack</h2>
          <table className="w-full text-[10px]">
            <thead>
              <tr className="border-b-2 border-slate-200 text-left">
                <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider">Module</th>
                <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-center">Category</th>
                <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-center">Units</th>
                <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-right">Cost</th>
                <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-right">Top Removal</th>
              </tr>
            </thead>
            <tbody>
              {calc.active.map(m => {
                const topK = CK.filter(k => m[k] > 0).sort((a, b) => m[b] - m[a])[0];
                return (
                  <tr key={m.id} className="border-b border-slate-100">
                    <td className="py-1.5 text-slate-700">
                      {m.icon} {m.name.trim()}
                    </td>
                    <td className="py-1.5 text-center">
                      <span className="px-1.5 rounded text-[8px] font-bold" style={{ background: CAT_COLORS[m.cat] + "18", color: CAT_COLORS[m.cat] }}>
                        {m.cat}
                      </span>
                    </td>
                    <td className="py-1.5 text-center font-mono text-slate-600">{m.units}</td>
                    <td className="py-1.5 text-right font-mono text-slate-800">{fmt(m.totalCost)}</td>
                    <td className="py-1.5 text-right font-mono" style={{ color: topK ? CONTAMINANT_COLORS[topK] : "#78909c" }}>
                      {topK ? `${topK.toUpperCase()} ${m[topK]}%` : "\u2014"}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </section>

        {/* ═══ 4. Projected Outcomes ═══ */}
        <section className="exec-card bg-white rounded-xl p-5 border border-slate-200 shadow-sm">
          <h2 className="text-xs font-bold text-slate-800 uppercase tracking-wider mb-3">Projected Outcomes</h2>
          <div className="grid grid-cols-4 gap-3 mb-4">
            {[
              { l: "Avg Reduction", v: calc.avg.toFixed(1) + "%", c: calc.met ? "text-green-700" : "text-orange-700" },
              { l: "Projected DO", v: calc.projDO.toFixed(1) + " mg/L", c: calc.projDO > 5 ? "text-green-700" : "text-orange-700" },
              { l: "GPM Deployed", v: fmtN(Math.round(calc.totGPM)), c: "text-blue-700" },
              { l: "PIN Teams", v: String(calc.teams), c: "text-slate-800" },
            ].map(x => (
              <div key={x.l} className="bg-slate-50 rounded-lg p-3 text-center">
                <div className="text-[8px] text-slate-400 uppercase tracking-wider">{x.l}</div>
                <div className={`text-lg font-bold font-mono ${x.c}`}>{x.v}</div>
              </div>
            ))}
          </div>

          {/* Before/after bars */}
          <div className="text-[9px] text-slate-400 uppercase tracking-wider font-mono mb-2">
            Contaminant Reduction (Before &rarr; After)
          </div>
          {CK.map(k => {
            if (ws.baseline[k] === 0) return null;
            const after = Math.max(0, ws.baseline[k] - (ws.baseline[k] * calc.ach[k] / 100));
            return (
              <div key={k} className="flex items-center gap-2 mb-1.5">
                <span className="w-16 text-[10px] text-slate-500 font-mono">{CONTAMINANT_LABELS[k].split(" / ")[0]}</span>
                <div className="flex-1 h-3 bg-slate-100 rounded-sm overflow-hidden relative">
                  <div className="absolute h-full rounded-sm opacity-20" style={{ width: `${ws.baseline[k]}%`, background: CONTAMINANT_COLORS[k] }} />
                  <div className="absolute h-full rounded-sm" style={{ width: `${after}%`, background: CONTAMINANT_COLORS[k], opacity: 0.8 }} />
                </div>
                <span className="w-20 text-[10px] font-mono text-slate-600 text-right">
                  {ws.baseline[k]}% &rarr; {after.toFixed(0)}%
                </span>
              </div>
            );
          })}
        </section>

        {/* ═══ 4b. Climate-Resilient Portfolio Analysis ═══ */}
        {climateScenario !== "baseline" && climateCalc && (() => {
          const proj = CLIMATE_PROJECTIONS[climateScenario][climateDecade];
          const scenarioLabel = climateScenario === "rcp45" ? "RCP 4.5" : "RCP 8.5";
          const highVuln = calc.active.filter(m => {
            const mod = MODULES.find(mm => mm.id === m.id);
            return mod?.climateVulnerability === "high";
          });
          const modVuln = calc.active.filter(m => {
            const mod = MODULES.find(mm => mm.id === m.id);
            return mod?.climateVulnerability === "moderate";
          });
          const lowVuln = calc.active.filter(m => {
            const mod = MODULES.find(mm => mm.id === m.id);
            return !mod?.climateVulnerability || mod.climateVulnerability === "low";
          });
          const avgDrop = calc.avg - climateCalc.avg;

          return (
            <section className="exec-card bg-white rounded-xl p-5 border border-slate-200 shadow-sm">
              <h2 className="text-xs font-bold text-slate-800 uppercase tracking-wider mb-3">
                Climate-Resilient Portfolio Analysis
              </h2>

              {/* Scenario header */}
              <div className="flex items-center gap-2 mb-4">
                <div className="w-1.5 h-1.5 rounded-full bg-amber-500" />
                <span className="text-sm font-bold text-slate-800">{scenarioLabel} &mdash; {climateDecade} Horizon</span>
              </div>

              {/* Forcing summary grid */}
              <div className="text-[9px] text-slate-400 uppercase tracking-wider font-mono mb-2">Climate Forcing Parameters</div>
              <div className="grid grid-cols-3 gap-3 mb-4">
                {[
                  { l: "Temp Increase", v: `+${proj.tempIncrease_F}°F` },
                  { l: "Precip Intensity", v: `+${proj.precipIntensityPct}%` },
                  { l: ws.salinity > 0 ? "Sea Level Rise" : "SLR (inland)", v: ws.salinity > 0 ? `+${proj.seaLevelRise_ft} ft` : "N/A" },
                ].map(x => (
                  <div key={x.l} className="text-center bg-amber-50 rounded-lg py-2 border border-amber-100">
                    <div className="text-[8px] text-slate-400 uppercase tracking-wider">{x.l}</div>
                    <div className="text-sm font-bold font-mono text-amber-700">{x.v}</div>
                  </div>
                ))}
              </div>

              {/* Watershed impact table */}
              <div className="text-[9px] text-slate-400 uppercase tracking-wider font-mono mb-2">Watershed Impact</div>
              <table className="w-full text-[10px] mb-4">
                <thead>
                  <tr className="border-b-2 border-slate-200 text-left">
                    <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider">Parameter</th>
                    <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-center">Baseline</th>
                    <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-center">Climate-Stressed</th>
                    <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-right">Delta</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-slate-100">
                    <td className="py-1.5 text-slate-700">Dissolved Oxygen</td>
                    <td className="py-1.5 text-center font-mono text-slate-600">{ws.doMgL} mg/L</td>
                    <td className="py-1.5 text-center font-mono text-amber-700">{climateWs.doMgL.toFixed(1)} mg/L</td>
                    <td className="py-1.5 text-right font-mono text-red-600">{(climateWs.doMgL - ws.doMgL).toFixed(1)}</td>
                  </tr>
                  <tr className="border-b border-slate-100">
                    <td className="py-1.5 text-slate-700">Flow</td>
                    <td className="py-1.5 text-center font-mono text-slate-600">{fmtN(ws.flowMGD)} MGD</td>
                    <td className="py-1.5 text-center font-mono text-amber-700">{fmtN(Math.round(climateWs.flowMGD))} MGD</td>
                    <td className="py-1.5 text-right font-mono text-amber-600">+{((climateWs.flowMGD / ws.flowMGD - 1) * 100).toFixed(0)}%</td>
                  </tr>
                  {ws.salinity > 0 && (
                    <tr className="border-b border-slate-100">
                      <td className="py-1.5 text-slate-700">Salinity</td>
                      <td className="py-1.5 text-center font-mono text-slate-600">{ws.salinity} ppt</td>
                      <td className="py-1.5 text-center font-mono text-amber-700">{climateWs.salinity.toFixed(1)} ppt</td>
                      <td className="py-1.5 text-right font-mono text-amber-600">+{(climateWs.salinity - ws.salinity).toFixed(1)}</td>
                    </tr>
                  )}
                </tbody>
              </table>

              {/* Performance comparison */}
              <div className="text-[9px] text-slate-400 uppercase tracking-wider font-mono mb-2">Performance Comparison</div>
              <table className="w-full text-[10px] mb-4">
                <thead>
                  <tr className="border-b-2 border-slate-200 text-left">
                    <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider">Contaminant</th>
                    <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-center">Baseline %</th>
                    <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-center">Stressed %</th>
                    <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-right">Delta</th>
                  </tr>
                </thead>
                <tbody>
                  {CK.map(k => {
                    if (ws.baseline[k] === 0) return null;
                    const delta = climateCalc.ach[k] - calc.ach[k];
                    return (
                      <tr key={k} className="border-b border-slate-100">
                        <td className="py-1.5 text-slate-700 font-mono">{CONTAMINANT_LABELS[k].split(" / ")[0]}</td>
                        <td className="py-1.5 text-center font-mono" style={{ color: CONTAMINANT_COLORS[k] }}>{calc.ach[k].toFixed(1)}%</td>
                        <td className="py-1.5 text-center font-mono text-amber-700">{climateCalc.ach[k].toFixed(1)}%</td>
                        <td className="py-1.5 text-right font-mono text-red-600">{delta.toFixed(1)}%</td>
                      </tr>
                    );
                  })}
                  <tr className="border-t-2 border-slate-300">
                    <td className="py-1.5 font-bold text-slate-800">Average</td>
                    <td className="py-1.5 text-center font-mono font-bold text-slate-800">{calc.avg.toFixed(1)}%</td>
                    <td className="py-1.5 text-center font-mono font-bold text-amber-700">{climateCalc.avg.toFixed(1)}%</td>
                    <td className="py-1.5 text-right font-mono font-bold text-red-600">{(climateCalc.avg - calc.avg).toFixed(1)}%</td>
                  </tr>
                </tbody>
              </table>

              {/* Module vulnerability groupings */}
              <div className="text-[9px] text-slate-400 uppercase tracking-wider font-mono mb-2">Module Vulnerability Assessment</div>
              <div className="space-y-2 mb-4">
                {highVuln.length > 0 && (
                  <div className="flex items-start gap-2">
                    <span className="text-[8px] bg-red-100 text-red-700 px-1.5 py-0.5 rounded font-bold shrink-0 mt-0.5">HIGH</span>
                    <span className="text-[10px] text-slate-600">{highVuln.map(m => m.name.trim()).join(", ")}</span>
                  </div>
                )}
                {modVuln.length > 0 && (
                  <div className="flex items-start gap-2">
                    <span className="text-[8px] bg-amber-100 text-amber-700 px-1.5 py-0.5 rounded font-bold shrink-0 mt-0.5">MOD</span>
                    <span className="text-[10px] text-slate-600">{modVuln.map(m => m.name.trim()).join(", ")}</span>
                  </div>
                )}
                {lowVuln.length > 0 && (
                  <div className="flex items-start gap-2">
                    <span className="text-[8px] bg-green-100 text-green-700 px-1.5 py-0.5 rounded font-bold shrink-0 mt-0.5">LOW</span>
                    <span className="text-[10px] text-slate-600">{lowVuln.map(m => m.name.trim()).join(", ")}</span>
                  </div>
                )}
              </div>

              {/* Climate-vulnerable callout */}
              {highVuln.length > 0 && (
                <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 mb-4">
                  <div className="text-[11px] font-bold text-amber-800 mb-1">Climate Vulnerability Warning</div>
                  <div className="text-[10px] text-amber-700 leading-relaxed">
                    {highVuln.length} high-vulnerability module{highVuln.length > 1 ? "s" : ""} in this portfolio.
                    Average reduction drops {avgDrop.toFixed(1)}% under {scenarioLabel}/{climateDecade}.
                    Consider supplementing nature-based systems with engineered treatment (PIN, MBR, DAF)
                    to maintain performance under climate stress.
                  </div>
                </div>
              )}

              {/* Adaptive management recommendations */}
              <div className="text-[9px] text-slate-400 uppercase tracking-wider font-mono mb-2">Adaptive Management Recommendations</div>
              <ul className="text-[10px] text-slate-600 space-y-1.5 list-disc pl-4">
                <li>Deploy additional PIN units to compensate for {avgDrop.toFixed(0)}% reduction loss under climate stress</li>
                <li>Prioritize engineered treatment over nature-based solutions for critical contaminant targets</li>
                {ws.salinity > 0 && (
                  <li>Monitor salinity intrusion — {(1.5 * proj.seaLevelRise_ft).toFixed(1)} ppt increase may exceed biological treatment tolerances</li>
                )}
                <li>Install supplemental aeration to offset {(0.1 * proj.tempIncrease_F).toFixed(1)} mg/L DO depression from warming</li>
                <li>Design stormwater infrastructure for +{proj.precipIntensityPct}% precipitation intensity (CSO +{proj.csoFreqIncreasePct}%)</li>
                <li>Schedule 5-year portfolio review against updated IPCC/NCA projections</li>
              </ul>
            </section>
          );
        })()}

        {/* ═══ 5. Cost Analysis ═══ */}
        <section className="exec-card bg-white rounded-xl p-5 border border-slate-200 shadow-sm">
          <h2 className="text-xs font-bold text-slate-800 uppercase tracking-wider mb-3">Cost Analysis</h2>

          {/* CapEx by category */}
          <div className="text-[9px] text-slate-400 uppercase tracking-wider font-mono mb-2">Capital Expenditure</div>
          {capexByCat.map(c => (
            <div key={c.cat} className="flex justify-between py-1 border-b border-slate-100">
              <div className="flex items-center gap-1.5">
                <div className="w-[3px] h-2.5 rounded-sm" style={{ background: CAT_COLORS[c.cat] }} />
                <span className="text-[10px] text-slate-600">{c.cat}</span>
              </div>
              <span className="text-[10px] font-mono font-semibold text-slate-800">{fmt(c.total)}</span>
            </div>
          ))}
          <div className="flex justify-between py-1.5 border-t-2 border-slate-300 mt-1">
            <span className="text-[10px] font-bold text-slate-800">Total CapEx</span>
            <span className="text-[11px] font-bold font-mono text-slate-800">{fmt(calc.capex)}</span>
          </div>

          {/* OpEx */}
          {calc.teams > 0 && (
            <div className="mt-4">
              <div className="text-[9px] text-slate-400 uppercase tracking-wider font-mono mb-2">Operating Expenditure</div>
              <div className="flex justify-between py-1 border-b border-slate-100">
                <span className="text-[10px] text-slate-600">PIN Teams ({calc.teams})</span>
                <span className="text-[10px] font-mono text-orange-700">{fmt(calc.annualOpex)}/yr</span>
              </div>
              <div className="flex justify-between py-1.5 border-t-2 border-slate-300 mt-1">
                <span className="text-[10px] font-bold text-slate-800">{timeline}-Year OpEx</span>
                <span className="text-[11px] font-bold font-mono text-orange-700">{fmt(calc.totalOpex)}</span>
              </div>
            </div>
          )}

          {/* Community */}
          {selectedEvents.length > 0 && (
            <div className="mt-4">
              <div className="text-[9px] text-slate-400 uppercase tracking-wider font-mono mb-2">Community Programs</div>
              <div className="flex justify-between py-1.5 border-t-2 border-slate-300">
                <span className="text-[10px] font-bold text-slate-800">{timeline}-Year Total</span>
                <span className="text-[11px] font-bold font-mono text-orange-700">{fmt(communityTotal)}</span>
              </div>
            </div>
          )}

          {/* Lifecycle */}
          <div className="mt-4 bg-slate-900 text-white rounded-lg p-4">
            <div className="flex justify-between items-baseline">
              <span className="text-xs font-bold">Lifecycle Total</span>
              <span className="text-xl font-bold font-mono">{fmt(lifecycleAll)}</span>
            </div>
            {calc.grantTotal > 0 && (
              <div className="flex justify-between items-baseline mt-1 pt-1 border-t border-slate-700">
                <span className="text-xs text-emerald-400">Net After Grants</span>
                <span className="text-lg font-bold font-mono text-emerald-400">{fmt(netAfterGrants)}</span>
              </div>
            )}
          </div>
        </section>

        {/* ═══ 6. Grants ═══ */}
        {calc.grants.length > 0 && (
          <section className="exec-card bg-white rounded-xl p-5 border border-slate-200 shadow-sm">
            <h2 className="text-xs font-bold text-slate-800 uppercase tracking-wider mb-3">Grant Opportunities</h2>
            <table className="w-full text-[10px]">
              <thead>
                <tr className="border-b-2 border-slate-200 text-left">
                  <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider">Program</th>
                  <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-center">Match Rate</th>
                  <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-right">Eligible CapEx</th>
                  <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-right">Est. Savings</th>
                </tr>
              </thead>
              <tbody>
                {calc.grants.map(g => (
                  <tr key={g.id} className="border-b border-slate-100">
                    <td className="py-1.5 text-slate-700">{g.name}</td>
                    <td className="py-1.5 text-center font-mono text-slate-600">{(g.match * 100).toFixed(0)}%</td>
                    <td className="py-1.5 text-right font-mono text-slate-600">{fmt(g.eligible)}</td>
                    <td className="py-1.5 text-right font-mono font-bold text-green-700">{fmt(g.savings)}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr className="border-t-2 border-slate-300">
                  <td colSpan={3} className="py-1.5 text-right font-bold text-slate-800">Total Grant Potential</td>
                  <td className="py-1.5 text-right font-bold font-mono text-green-700">{fmt(calc.grantTotal)}</td>
                </tr>
              </tfoot>
            </table>
          </section>
        )}

        {/* ═══ 7. Partnerships ═══ */}
        {selectedNGOs.length > 0 && (
          <section className="exec-card bg-white rounded-xl p-5 border border-slate-200 shadow-sm">
            <h2 className="text-xs font-bold text-slate-800 uppercase tracking-wider mb-3">NGO Partnerships</h2>
            <table className="w-full text-[10px]">
              <thead>
                <tr className="border-b-2 border-slate-200 text-left">
                  <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider">Organization</th>
                  <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider">Type</th>
                  <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-right">In-Kind Value</th>
                </tr>
              </thead>
              <tbody>
                {selectedNGOs.map(n => (
                  <tr key={n.id} className="border-b border-slate-100">
                    <td className="py-1.5 text-slate-700">{n.icon} {n.name}</td>
                    <td className="py-1.5 text-slate-500">{n.type}</td>
                    <td className="py-1.5 text-right font-mono text-green-700">{fmt(n.value)}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr className="border-t-2 border-slate-300">
                  <td colSpan={2} className="py-1.5 text-right font-bold text-slate-800">Total In-Kind Value</td>
                  <td className="py-1.5 text-right font-bold font-mono text-green-700">{fmt(ngoValue)}</td>
                </tr>
              </tfoot>
            </table>
          </section>
        )}

        {/* ═══ 8. Community Programs ═══ */}
        {selectedEvents.length > 0 && (
          <section className="exec-card bg-white rounded-xl p-5 border border-slate-200 shadow-sm">
            <h2 className="text-xs font-bold text-slate-800 uppercase tracking-wider mb-3">Community Programs</h2>
            <table className="w-full text-[10px]">
              <thead>
                <tr className="border-b-2 border-slate-200 text-left">
                  <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider">Program</th>
                  <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-center">Frequency</th>
                  <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-center">Volunteers</th>
                  <th className="py-1.5 text-slate-400 font-mono uppercase tracking-wider text-right">Annual Cost</th>
                </tr>
              </thead>
              <tbody>
                {selectedEvents.map(e => (
                  <tr key={e.id} className="border-b border-slate-100">
                    <td className="py-1.5 text-slate-700">{e.icon} {e.name}</td>
                    <td className="py-1.5 text-center text-slate-500">{e.freq}</td>
                    <td className="py-1.5 text-center font-mono text-slate-600">{e.volunteers}</td>
                    <td className="py-1.5 text-right font-mono text-orange-700">{fmt(e.cost)}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr className="border-t-2 border-slate-300">
                  <td colSpan={3} className="py-1.5 text-right font-bold text-slate-800">Annual Total</td>
                  <td className="py-1.5 text-right font-bold font-mono text-orange-700">{fmt(evtCostYr)}</td>
                </tr>
              </tfoot>
            </table>
          </section>
        )}

        {/* ═══ 9. Target Achievement ═══ */}
        <section className="exec-card">
          <div className={`rounded-xl p-5 border-2 ${calc.met ? "bg-green-50 border-green-300" : "bg-amber-50 border-amber-300"}`}>
            <h2 className={`text-sm font-bold mb-2 ${calc.met ? "text-green-800" : "text-amber-800"}`}>
              {calc.met ? "\u2713 Target Achievement: ON TRACK" : "\u26A0 Target Achievement: BELOW TARGET"}
            </h2>
            <div className="grid grid-cols-3 gap-4 mb-3">
              <div>
                <div className="text-[9px] text-slate-400 uppercase">Target</div>
                <div className="text-lg font-bold font-mono text-slate-800">{target}%</div>
              </div>
              <div>
                <div className="text-[9px] text-slate-400 uppercase">Projected</div>
                <div className={`text-lg font-bold font-mono ${calc.met ? "text-green-700" : "text-amber-700"}`}>
                  {calc.avg.toFixed(1)}%
                </div>
              </div>
              <div>
                <div className="text-[9px] text-slate-400 uppercase">Gap</div>
                <div className={`text-lg font-bold font-mono ${calc.met ? "text-green-700" : "text-amber-700"}`}>
                  {calc.met ? "+" : ""}{(calc.avg - target).toFixed(1)}%
                </div>
              </div>
            </div>
            {!calc.met && (
              <div className="text-xs text-amber-700 leading-relaxed">
                <strong>Recommendations:</strong> Increase PIN unit count, add source control modules
                (agricultural BMPs, septic upgrades), or deploy additional biological treatment
                (constructed wetlands, algal turf scrubbers) to close the gap.
              </div>
            )}
          </div>
        </section>

        {/* ═══ 10. Disclaimer ═══ */}
        <section className="exec-card border-t border-slate-200 pt-4">
          <div className="text-[9px] text-slate-400 leading-relaxed space-y-1">
            <p>
              <strong>Disclaimer:</strong> This treatment plan was generated by PIN (PEARL Intelligence Network)
              for planning purposes only. It does not constitute a regulatory determination, legal opinion,
              or engineering design. All cost estimates are planning-level approximations based on industry
              averages and manufacturer data.
            </p>
            <p>
              Contaminant reduction projections are modeled estimates based on published removal rates and
              site-specific flow/salinity parameters. Actual performance will vary based on installation,
              maintenance, and environmental conditions. Verify all data with primary agency sources and
              qualified environmental engineers before proceeding with implementation.
            </p>
            {climateScenario !== "baseline" && (
              <p>
                Climate projections are simplified planning-level estimates based on IPCC AR6 and NCA5 scenario
                data. They do not represent site-specific downscaled climate models. Module vulnerability
                ratings are generalized and may not reflect local conditions. Consult regional climate
                assessments for project-level design.
              </p>
            )}
            <p className="text-slate-300">
              &copy; {new Date().getFullYear()} Local Seafood Projects Inc. Project PEARL&trade;, ALIA&trade;
              are trademarks of Local Seafood Projects.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
